// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxDFUZvhus6NmtZsVx-Zg7sHc53QU7vbI',
    appId: '1:435982348302:web:c867c676e163d41e7d0c5f',
    messagingSenderId: '435982348302',
    projectId: 'socialapptutorial-5dbbc',
    authDomain: 'socialapptutorial-5dbbc.firebaseapp.com',
    storageBucket: 'socialapptutorial-5dbbc.firebasestorage.app',
    measurementId: 'G-Q67WP3PQ1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjFf14dUqFiNjO0oFkamZWDMT6N7fWMNk',
    appId: '1:435982348302:android:36887f06b627c1dc7d0c5f',
    messagingSenderId: '435982348302',
    projectId: 'socialapptutorial-5dbbc',
    storageBucket: 'socialapptutorial-5dbbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArcu8ehQdp1OUjqdCB5Jjgua610zw75Bg',
    appId: '1:435982348302:ios:c9ce66583c0990427d0c5f',
    messagingSenderId: '435982348302',
    projectId: 'socialapptutorial-5dbbc',
    storageBucket: 'socialapptutorial-5dbbc.firebasestorage.app',
    iosBundleId: 'com.example.bundeerv1',
  );
}
